---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: exampleSite/content/english/author
  label: Votre réponse
  create: documents
  match: "**/*"
  templates:
  - author
- type: directory
  path: exampleSite/content/english/blog
  label: Logements
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: exampleSite/content/french/blog
  label: Transport
  create: documents
  match: "**/*"
  templates:
  - post
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
